// Generated 17/01/2025 GMT

/*
 * Copyright © 2025, Microchip Technology Inc. and its subsidiaries ("Microchip")
 * All rights reserved.
 * 
 * This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
 * 
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 * 
 *     1. Redistributions of source code must retain the above copyright notice, this list of
 *        conditions and the following disclaimer.
 * 
 *     2. Redistributions in binary form must reproduce the above copyright notice, this list
 *        of conditions and the following disclaimer in the documentation and/or other
 *        materials provided with the distribution. Publication is not required when
 *        this file is used in an embedded application.
 * 
 *     3. Microchip's name may not be used to endorse or promote products derived from this
 *        software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef _PIC18_CHIP_SELECT_INC_
#define _PIC18_CHIP_SELECT_INC_

#define _HEADER_NOT_FOUND

#ifdef _18F1220
#include <pic18f1220.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F1230
#include <pic18f1230.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F1320
#include <pic18f1320.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F1330
#include <pic18f1330.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2220
#include <pic18f2220.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2221
#include <pic18f2221.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2320
#include <pic18f2320.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2321
#include <pic18f2321.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2331
#include <pic18f2331.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2410
#include <pic18f2410.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F242
#include <pic18f242.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2420
#include <pic18f2420.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2423
#include <pic18f2423.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2431
#include <pic18f2431.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2439
#include <pic18f2439.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2450
#include <pic18f2450.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2455
#include <pic18f2455.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2458
#include <pic18f2458.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F248
#include <pic18f248.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2480
#include <pic18f2480.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2510
#include <pic18f2510.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2515
#include <pic18f2515.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F252
#include <pic18f252.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2520
#include <pic18f2520.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2523
#include <pic18f2523.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2525
#include <pic18f2525.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2539
#include <pic18f2539.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2550
#include <pic18f2550.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2553
#include <pic18f2553.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F258
#include <pic18f258.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2580
#include <pic18f2580.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2585
#include <pic18f2585.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2610
#include <pic18f2610.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2620
#include <pic18f2620.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2680
#include <pic18f2680.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2682
#include <pic18f2682.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F2685
#include <pic18f2685.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4220
#include <pic18f4220.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4221
#include <pic18f4221.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4320
#include <pic18f4320.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4321
#include <pic18f4321.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4331
#include <pic18f4331.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4410
#include <pic18f4410.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F442
#include <pic18f442.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4420
#include <pic18f4420.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4423
#include <pic18f4423.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4431
#include <pic18f4431.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4439
#include <pic18f4439.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4450
#include <pic18f4450.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4455
#include <pic18f4455.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4458
#include <pic18f4458.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F448
#include <pic18f448.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4480
#include <pic18f4480.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4510
#include <pic18f4510.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4515
#include <pic18f4515.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F452
#include <pic18f452.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4520
#include <pic18f4520.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4523
#include <pic18f4523.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4525
#include <pic18f4525.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4539
#include <pic18f4539.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4550
#include <pic18f4550.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4553
#include <pic18f4553.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F458
#include <pic18f458.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4580
#include <pic18f4580.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4585
#include <pic18f4585.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4610
#include <pic18f4610.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4620
#include <pic18f4620.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4680
#include <pic18f4680.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4682
#include <pic18f4682.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F4685
#include <pic18f4685.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6310
#include <pic18f6310.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6390
#include <pic18f6390.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6393
#include <pic18f6393.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6410
#include <pic18f6410.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6490
#include <pic18f6490.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6493
#include <pic18f6493.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6520
#include <pic18f6520.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6525
#include <pic18f6525.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6527
#include <pic18f6527.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6585
#include <pic18f6585.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6620
#include <pic18f6620.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6621
#include <pic18f6621.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6622
#include <pic18f6622.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6627
#include <pic18f6627.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6628
#include <pic18f6628.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6680
#include <pic18f6680.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6720
#include <pic18f6720.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6722
#include <pic18f6722.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F6723
#include <pic18f6723.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8310
#include <pic18f8310.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8390
#include <pic18f8390.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8393
#include <pic18f8393.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8410
#include <pic18f8410.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8490
#include <pic18f8490.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8493
#include <pic18f8493.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8520
#include <pic18f8520.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8525
#include <pic18f8525.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8527
#include <pic18f8527.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8585
#include <pic18f8585.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8620
#include <pic18f8620.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8621
#include <pic18f8621.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8622
#include <pic18f8622.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8627
#include <pic18f8627.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8628
#include <pic18f8628.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8680
#include <pic18f8680.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8720
#include <pic18f8720.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8722
#include <pic18f8722.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F8723
#include <pic18f8723.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF1220
#include <pic18lf1220.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF1230
#include <pic18lf1230.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF1320
#include <pic18lf1320.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF1330
#include <pic18lf1330.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2220
#include <pic18lf2220.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2221
#include <pic18lf2221.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2320
#include <pic18lf2320.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2321
#include <pic18lf2321.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2331
#include <pic18lf2331.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2410
#include <pic18lf2410.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF242
#include <pic18lf242.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2420
#include <pic18lf2420.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2423
#include <pic18lf2423.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2431
#include <pic18lf2431.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2439
#include <pic18lf2439.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2450
#include <pic18lf2450.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2455
#include <pic18lf2455.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2458
#include <pic18lf2458.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF248
#include <pic18lf248.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2480
#include <pic18lf2480.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2510
#include <pic18lf2510.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2515
#include <pic18lf2515.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF252
#include <pic18lf252.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2520
#include <pic18lf2520.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2523
#include <pic18lf2523.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2525
#include <pic18lf2525.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2539
#include <pic18lf2539.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2550
#include <pic18lf2550.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2553
#include <pic18lf2553.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF258
#include <pic18lf258.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2580
#include <pic18lf2580.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2585
#include <pic18lf2585.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2610
#include <pic18lf2610.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2620
#include <pic18lf2620.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2680
#include <pic18lf2680.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2682
#include <pic18lf2682.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF2685
#include <pic18lf2685.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4220
#include <pic18lf4220.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4221
#include <pic18lf4221.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4320
#include <pic18lf4320.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4321
#include <pic18lf4321.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4331
#include <pic18lf4331.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4410
#include <pic18lf4410.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF442
#include <pic18lf442.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4420
#include <pic18lf4420.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4423
#include <pic18lf4423.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4431
#include <pic18lf4431.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4439
#include <pic18lf4439.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4450
#include <pic18lf4450.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4455
#include <pic18lf4455.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4458
#include <pic18lf4458.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF448
#include <pic18lf448.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4480
#include <pic18lf4480.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4510
#include <pic18lf4510.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4515
#include <pic18lf4515.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF452
#include <pic18lf452.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4520
#include <pic18lf4520.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4523
#include <pic18lf4523.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4525
#include <pic18lf4525.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4539
#include <pic18lf4539.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4550
#include <pic18lf4550.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4553
#include <pic18lf4553.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF458
#include <pic18lf458.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4580
#include <pic18lf4580.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4585
#include <pic18lf4585.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4610
#include <pic18lf4610.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4620
#include <pic18lf4620.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4680
#include <pic18lf4680.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4682
#include <pic18lf4682.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF4685
#include <pic18lf4685.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6310
#include <pic18lf6310.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6390
#include <pic18lf6390.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6393
#include <pic18lf6393.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6410
#include <pic18lf6410.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6490
#include <pic18lf6490.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6493
#include <pic18lf6493.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6520
#include <pic18lf6520.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6525
#include <pic18lf6525.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6527
#include <pic18lf6527.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6585
#include <pic18lf6585.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6620
#include <pic18lf6620.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6621
#include <pic18lf6621.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6622
#include <pic18lf6622.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6627
#include <pic18lf6627.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6628
#include <pic18lf6628.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6680
#include <pic18lf6680.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6720
#include <pic18lf6720.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6722
#include <pic18lf6722.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF6723
#include <pic18lf6723.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8310
#include <pic18lf8310.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8390
#include <pic18lf8390.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8393
#include <pic18lf8393.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8410
#include <pic18lf8410.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8490
#include <pic18lf8490.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8493
#include <pic18lf8493.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8520
#include <pic18lf8520.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8525
#include <pic18lf8525.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8527
#include <pic18lf8527.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8585
#include <pic18lf8585.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8620
#include <pic18lf8620.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8621
#include <pic18lf8621.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8622
#include <pic18lf8622.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8627
#include <pic18lf8627.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8628
#include <pic18lf8628.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8680
#include <pic18lf8680.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8720
#include <pic18lf8720.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8722
#include <pic18lf8722.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18LF8723
#include <pic18lf8723.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _TEST_CHIP_
#undef _HEADER_NOT_FOUND
#endif

#ifdef _HEADER_NOT_FOUND
#error Device-specific header could not be found for target chip
#endif

#endif // _PIC18_CHIP_SELECT_INC_
